[2024-06-16T14:13:24.747+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: simple-etl-dag.extract manual__2024-06-16T12:01:56.354626+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
